// Member PsuedoCode

# CRUD Actions

# a) Create
# Member details(first/last name, age, gender, membership, picture, contact) to be
# taken and submitted into SQL database using SQL runner. DB will return autogenerated ID
# b) Read
# User can find member by ID in SQL DB using SQL runner
# c) Update
# User can access member by ID using SQL runner and update any individual element
# d) Delete
# User can delete member using ID in the SQL database using the SQL runner
